services:
  api:
    build: .
    container_name: cinema_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - mailhog
      - minio
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: cinema_db
    environment:
      POSTGRES_DB: ${DB_NAME:-cinema}
      POSTGRES_USER: ${DB_USER:-cinema}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-cinema}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: cinema_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  celery_worker:
    build: .
    container_name: cinema_celery_worker
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - mailhog
    command: >
      celery -A app.core.celery_app.celery worker --loglevel=INFO
    volumes:
      - .:/app
    restart: unless-stopped

  celery_beat:
    build: .
    container_name: cinema_celery_beat
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: >
      celery -A app.core.celery_app.celery beat --loglevel=INFO
    volumes:
      - .:/app
      - celery_beat_data:/app/.celerybeat
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: cinema_mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # UI
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2025-01-20T14-49-07Z
    container_name: cinema_minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped

volumes:
  db_data:
  minio_data:
  celery_beat_data:
